name: tuutal
channels:
  - defaults
dependencies:
  - pip=24.0
  - python=3.10.0
  - setuptools=69.5.1
  - pip:
      - maturin==1.7.0
      - numpy==2.0.0
      - pytest==8.3.2
      - scipy==1.13.1
      - tomli==2.0.1
