name: Build Wheels Ubuntu

on:
  push:
    branches: [dev]
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
        interpreter: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.interpreter }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: >
            --release
            --manifest-path py-tuutal/Cargo.toml
            --out dist
            --interpreter ${{ matrix.interpreter }}
          manylinux: auto

      - name: Test wheel
        # Only test on x86-64 for now as this matches the runner architecture
        if: matrix.platform.target == 'x86-64'
        run: |
          pip install --force-reinstall --verbose dist/*.whl
          python -c 'import tuutal'
